### ISSUE TITLE
How to use buji with springboot ?

### ISSUE THREAD

**Issue by zhaoshg** [pac4j/buji-pac4j-demo#17]
How to use buji with springboot ?  I can't find any demo from internet.

my code:
1. a Listener extends org.apache.shiro.web.env.EnvironmentLoaderListener  with @WebListener . 
2. a Filter extends org.apache.shiro.web.servlet.ShiroFilter with @WebFilter
3. add @ServletComponentScan for my Application 
4. remove all SecurityFilter configurations  except casSecurityFilter .

it seems like springboot can not load shiro.ini.  

```

2017-08-03 11:51:19.357  INFO 8408 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'requestContextFilter' to: [/*]
2017-08-03 11:51:19.358  INFO 8408 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'webStatFilter' to urls: [/*]
2017-08-03 11:51:19.358  INFO 8408 --- [ost-startStop-1] o.s.b.w.servlet.FilterRegistrationBean   : Mapping filter: 'shiroFilter' to urls: [/*]
2017-08-03 11:51:19.374  INFO 8408 --- [ost-startStop-1] o.a.c.c.C.[Tomcat].[localhost].[/]       : Initializing Shiro environment
2017-08-03 11:51:19.374  INFO 8408 --- [ost-startStop-1] o.a.shiro.web.env.EnvironmentLoader      : Starting Shiro environment initialization.
2017-08-03 11:51:19.515  WARN 8408 --- [ost-startStop-1] org.pac4j.core.matching.PathMatcher      : Excluding paths with regexes is an advanced feature: be careful when defining your regular expression to avoid any security issues!
2017-08-03 11:51:19.518 ERROR 8408 --- [ost-startStop-1] o.a.shiro.web.env.EnvironmentLoader      : Shiro environment initialization failed

java.lang.IllegalArgumentException: Configuration error.  Specified object [config] with property [authorizers] without first defining that object's class.  Please first specify the class property first, e.g. myObject = fully_qualified_class_name and then define additional properties.
	at org.apache.shiro.config.ReflectionBuilder.applySingleProperty(ReflectionBuilder.java:203) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.ReflectionBuilder.applyProperty(ReflectionBuilder.java:167) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.ReflectionBuilder.buildObjects(ReflectionBuilder.java:124) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.IniSecurityManagerFactory.buildInstances(IniSecurityManagerFactory.java:161) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:124) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.IniSecurityManagerFactory.createSecurityManager(IniSecurityManagerFactory.java:102) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:88) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.IniSecurityManagerFactory.createInstance(IniSecurityManagerFactory.java:46) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.config.IniFactorySupport.createInstance(IniFactorySupport.java:123) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.util.AbstractFactory.getInstance(AbstractFactory.java:47) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.env.IniWebEnvironment.createWebSecurityManager(IniWebEnvironment.java:203) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.env.IniWebEnvironment.configure(IniWebEnvironment.java:99) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.env.IniWebEnvironment.init(IniWebEnvironment.java:92) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:45) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.util.LifecycleUtils.init(LifecycleUtils.java:40) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.env.EnvironmentLoader.createEnvironment(EnvironmentLoader.java:221) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.env.EnvironmentLoader.initEnvironment(EnvironmentLoader.java:133) ~[shiro-all-1.2.4.jar:1.2.4]
	at org.apache.shiro.web.env.EnvironmentLoaderListener.contextInitialized(EnvironmentLoaderListener.java:58) [shiro-all-1.2.4.jar:1.2.4]
	at org.apache.catalina.core.StandardContext.listenerStart(StandardContext.java:4743) [tomcat-embed-core-8.5.16.jar:8.5.16]
	at org.apache.catalina.core.StandardContext.startInternal(StandardContext.java:5207) [tomcat-embed-core-8.5.16.jar:8.5.16]
	at org.apache.catalina.util.LifecycleBase.start(LifecycleBase.java:150) [tomcat-embed-core-8.5.16.jar:8.5.16]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1419) [tomcat-embed-core-8.5.16.jar:8.5.16]
	at org.apache.catalina.core.ContainerBase$StartChild.call(ContainerBase.java:1409) [tomcat-embed-core-8.5.16.jar:8.5.16]
	at java.util.concurrent.FutureTask.run(FutureTask.java:266) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_111]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_111]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_111]
```

**Comment by leleuj** [comment]
I guess it should not be too different from a Shiro + Spring Boot demo when using buji-pac4j.

That said, the error you have makes me think about the automatic loading we have with Shiro using the `org.apache.shiro.web.env.WebEnvironment` file: https://github.com/bujiio/buji-pac4j/blob/master/src/main/resources/META-INF/services/org.apache.shiro.web.env.WebEnvironment, which loads the https://github.com/bujiio/buji-pac4j/blob/master/src/main/resources/buji-pac4j-default.ini file which contains the missing components in your case.

This may be the issue here. Explicitly add these components to your `shiro.ini` file or update your configuration appropriately and keep us posted.

**Comment by zhaoshg** [comment]
the reason is 
```xml
 <dependency>
            <groupId>net.mingsoft</groupId>
            <artifactId>shiro-freemarker-tags</artifactId>
            <version>0.1</version>
        </dependency>
``` 
shiro-freemarker-tags  use  shiro1.2.4 ,not 1.4.0
