### ISSUE TITLE
SAML integration with okta Identity provider is not working. 

### ISSUE THREAD

**Issue by vganesh** [pac4j/buji-pac4j-demo#8]
Hello Jerome, 

I am able to test buji-pac4j-demo with Facebook successfully. Thanks. 

However, I am NOT able to test it okta identity provider (https://www.okta.com/). After registering a developer account with okta, I got four parameters from IdP 
1. Identity Provider Single Sign-On URL 
2. Identity Provider Issuer 
3. X.509 Certificate and 
4. IDP metadata. 

I used these parameters and made changes to **src/main/resources/testshib-providers.xml** . Since **Saml2Client.java** says it relies on SSO, I installed SSO version of tomcat on my laptop, built this project by running the command **mvn clean install** and deployed **buji-pac4j-demo.war** in the webapps directory. 

I can verify the secured URL https://localhost:8443/buji-pac4j-demo/ works correctly and the index is displayed. Thanks, 

In the instance of Okta app, I specified Single Sign On URL as https://localhost:8443/buji-pac4j-demo/callback?client_name=Saml2Client&needs_client_redirection=true

Now, when I go to the local URL instance on my laptop https://localhost:8443/buji-pac4j-demo/callback?client_name=Saml2Client&needs_client_redirection=true , enter the valid login credentials for Okta IdP provider and watch network traffic, I can see tomcat webapp on my laptop is connecting to the Okta URL I have specified in **testshib-providers.xml** which pass the URL
 https://localhost:8443/buji-pac4j-demo/callbackclient_name=Saml2Client&needs_client_redirection=true '
back to pac4j-saml library and then it enters in loop and there is a constant interaction between Okta application and pack4j-saml library as if it has entered in a infinite loop and the screen keeps blinking. :-(

Can you please tell me what configuration parameter must be changed either in the xml file or at Okta Application configuration page, so that interaction between pack4j-saml and IdP provider like Okta will be successful? 

By the way, when I test SAML integration with the code from https://github.com/pac4j/buji-pac4j-demo as is, (no changes to the xml configuration file) and when I try to login to https://idp.testshib.org/idp/shibboleth , the error is shown below. If you can let me know what needs to be done to test SAML integration with this demo program, as is, to get it working and the login to be successful, that will be helpful. I am testing with the latest code from github. 

Thanks and regards, 
Ganesh 

BUJI PAC4J DEMO 18:03:09.460 [http-nio-8443-exec-10] DEBUG io.buji.pac4j.ClientFilter - requires HTTP action : {}
org.pac4j.core.exception.RequiresHttpAction: Needs client redirection
	at org.pac4j.core.exception.RequiresHttpAction.ok(RequiresHttpAction.java:75) ~[pac4j-core-1.7.0.jar:na]
	at org.pac4j.core.client.BaseClient.getCredentials(BaseClient.java:213) ~[pac4j-core-1.7.0.jar:na]
	at io.buji.pac4j.ClientFilter.createToken(ClientFilter.java:75) ~[buji-pac4j-servlet-1.3.1.jar:na]
	at io.buji.pac4j.ClientFilter.onAccessDenied(ClientFilter.java:92) ~[buji-pac4j-servlet-1.3.1.jar:na]
	at org.apache.shiro.web.filter.AccessControlFilter.onAccessDenied(AccessControlFilter.java:133) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:203) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:178) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.28]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.28]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.28]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.28]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.28]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.28]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-coyote.jar:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.28]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.28]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]

**Comment by leleuj** [comment]
You should not define this url at your identity provider: `https://localhost:8443/buji-pac4j-demo/callback?client_name=Saml2Client&needs_client_redirection=true`.
The additional `needs_client_redirection=true` is used to delay the computation of the redirection url to the identity provider.

Can you try defining this url instead: `https://localhost:8443/buji-pac4j-demo/callback?client_name=Saml2Client`?

@mmoayyed : I see that the SAML client is defined without direct redirection (https://github.com/pac4j/pac4j/blob/master/pac4j-saml/src/main/java/org/pac4j/saml/client/SAML2Client.java#L223), it means that when we try to access a protected resource, the redirection url is first to the callback url with the additional parameter: `needs_client_redirection=true` then to the IdP (assuming that computing this second redirection url has a cost because it requires a communication with the IdP): shouldn't the SAML client use direct redrection?

**Comment by leleuj** [comment]
One more thing: the configuration with testshib is currently broken, so the demo: https://github.com/pac4j/buji-pac4j-demo won't work correctly for SAML support.

**Comment by vganesh** [comment]
Thanks Jerome. As suggested by you, I changed the Url at my identity provider to 
https://localhost:8443/buji-pac4j-demo/callbackclient_name=Saml2Client . Doing so, I can verify the webapp running on my laptop, is able to successfully login to the IdP application which redirects it to the URL specified above without "needs_client_redirection" parameters and then the error is: internal error. :-(  

I see the following error in catalina.log file. This is the same error I see with testshib without any of my changes in the configuration file. It should be possible for people testing this software to reproduce this error by just testing the SAML integration from https://github.com/pac4j/buji-pac4j-demo as is. Can you please explain what must be the correct configuration in testshib? I cannot change or see the configuration in testshib but at least I can test it with IdP configuration I have access to. 

The way I understand how this software works is, in my example the URL https://localhost:8443/buji-pac4j-demo/callback?client_name=Saml2Client&needs_client_redirection=true will correctly direct this software to send the request to the IdP. However, when the IdP send the URL https://localhost:8443/buji-pac4j-demo/callback?client_name=Saml2Client as a response, then this software will fail with the error message "Needs client redirection" in the log file. It is not clear to me what needs to be done either in the configuration file or in the code, to fix this issue. I think you had mentioned in one of the e-mail communication that you got it working in your instance that indicates that there is no issue with the code and so it looks like there is something wrong in the IdP configuration? 


From catalina.log file 
===============

BUJI PAC4J DEMO 08:14:11.682 [http-nio-8443-exec-10] DEBUG io.buji.pac4j.ClientFilter - client : <Saml2Client> | callbackUrl: http://localhost:8080/callback?client_name=Saml2Client | name: null | isDirectRedirection: false | enableContextualRedirects: false |
BUJI PAC4J DEMO 08:15:20.404 [http-nio-8443-exec-3] DEBUG io.buji.pac4j.ClientFilter - client : <Saml2Client> | callbackUrl: http://localhost:8080/callback?client_name=Saml2Client | name: null | isDirectRedirection: false | enableContextualRedirects: false |
BUJI PAC4J DEMO 08:15:20.414 [http-nio-8443-exec-3] DEBUG io.buji.pac4j.ClientFilter - requires HTTP action : {}
org.pac4j.core.exception.RequiresHttpAction: Needs client redirection
	at org.pac4j.core.exception.RequiresHttpAction.ok(RequiresHttpAction.java:75) ~[pac4j-core-1.7.0.jar:na]
	at org.pac4j.core.client.BaseClient.getCredentials(BaseClient.java:213) ~[pac4j-core-1.7.0.jar:na]
	at io.buji.pac4j.ClientFilter.createToken(ClientFilter.java:75) ~[buji-pac4j-servlet-1.3.1.jar:na]
	at io.buji.pac4j.ClientFilter.onAccessDenied(ClientFilter.java:92) ~[buji-pac4j-servlet-1.3.1.jar:na]
	at org.apache.shiro.web.filter.AccessControlFilter.onAccessDenied(AccessControlFilter.java:133) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.filter.AccessControlFilter.onPreHandle(AccessControlFilter.java:162) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.filter.PathMatchingFilter.isFilterChainContinued(PathMatchingFilter.java:203) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.filter.PathMatchingFilter.preHandle(PathMatchingFilter.java:178) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AdviceFilter.doFilterInternal(AdviceFilter.java:131) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.ProxiedFilterChain.doFilter(ProxiedFilterChain.java:66) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.executeChain(AbstractShiroFilter.java:449) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter$1.call(AbstractShiroFilter.java:365) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.SubjectCallable.doCall(SubjectCallable.java:90) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.SubjectCallable.call(SubjectCallable.java:83) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.subject.support.DelegatingSubject.execute(DelegatingSubject.java:383) [shiro-core-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.AbstractShiroFilter.doFilterInternal(AbstractShiroFilter.java:362) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.shiro.web.servlet.OncePerRequestFilter.doFilter(OncePerRequestFilter.java:125) [shiro-web-1.2.3.jar:1.2.3]
	at org.apache.catalina.core.ApplicationFilterChain.internalDoFilter(ApplicationFilterChain.java:239) [catalina.jar:8.0.28]
	at org.apache.catalina.core.ApplicationFilterChain.doFilter(ApplicationFilterChain.java:206) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardWrapperValve.invoke(StandardWrapperValve.java:217) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardContextValve.invoke(StandardContextValve.java:106) [catalina.jar:8.0.28]
	at org.apache.catalina.authenticator.AuthenticatorBase.invoke(AuthenticatorBase.java:502) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardHostValve.invoke(StandardHostValve.java:142) [catalina.jar:8.0.28]
	at org.apache.catalina.valves.ErrorReportValve.invoke(ErrorReportValve.java:79) [catalina.jar:8.0.28]
	at org.apache.catalina.valves.AbstractAccessLogValve.invoke(AbstractAccessLogValve.java:616) [catalina.jar:8.0.28]
	at org.apache.catalina.core.StandardEngineValve.invoke(StandardEngineValve.java:88) [catalina.jar:8.0.28]
	at org.apache.catalina.connector.CoyoteAdapter.service(CoyoteAdapter.java:518) [catalina.jar:8.0.28]
	at org.apache.coyote.http11.AbstractHttp11Processor.process(AbstractHttp11Processor.java:1091) [tomcat-coyote.jar:8.0.28]
	at org.apache.coyote.AbstractProtocol$AbstractConnectionHandler.process(AbstractProtocol.java:673) [tomcat-coyote.jar:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.doRun(NioEndpoint.java:1500) [tomcat-coyote.jar:8.0.28]
	at org.apache.tomcat.util.net.NioEndpoint$SocketProcessor.run(NioEndpoint.java:1456) [tomcat-coyote.jar:8.0.28]
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142) [na:1.8.0_60]
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617) [na:1.8.0_60]
	at org.apache.tomcat.util.threads.TaskThread$WrappingRunnable.run(TaskThread.java:61) [tomcat-util.jar:8.0.28]
	at java.lang.Thread.run(Thread.java:745) [na:1.8.0_60]
BUJI PAC4J DEMO 08:15:21.135 [http-nio-8443-exec-2] DEBUG io.buji.pac4j.ClientFilter - client : <Saml2Client> | callbackUrl: http://localhost:8080/callback?client_name=Saml2Client | name: null | isDirectRedirection: false | enableContextualRedirects: false |

----------------------------------------------------------------------------------------

If I had a JSP to dump the parameters and from IdP site, if I change the URL at IdP to hit the dumpParameters.jsp, then the output is shown below. The SAMLResponse is null and SecurityUtils.getSubject().getPrincipals() is null :-( . I guess this is due to the error "Needs client redirection" shown above?

The information sent by IdP to IP is shown below. 
====================================
HTTP Header Request Example

Header Name	Header Value(s)
Origin	https://dev-270292.oktapreview.com
Cookie	JSESSIONID=mlcqptjnhzpr1a9fo9iejmm4l
Accept	text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Connection	keep-alive
User-Agent	Mozilla/5.0 (Macintosh; Intel Mac OS X 10_10_5) AppleWebKit/601.2.7 (KHTML, like Gecko) Version/9.0.1 Safari/601.2.7
Host	localhost:8080
Accept-Language	en-us
Accept-Encoding	gzip, deflate
Content-Length	9309
Content-Type	application/x-www-form-urlencoded
Reading Cookies

Found Cookies Name and Value

Name : JSESSIONID, Value: mlcqptjnhzpr1a9fo9iejmm4l 
HTTP Parameters Request Example

Param Name	Param Value(s)
RelayState	null
SAMLResponse	null

**Comment by leleuj** [comment]
I'm in holidays: maybe @miremond might help you on this SAML configuration...

**Comment by vganesh** [comment]
I am able to test authentication using SAMP protocol from this webapp to Okta Identity provider. Here are the steps I followed. 

1. Create a developer account at https://www.okta.com/developer/signup/
2. Create an app at Okta site that will communicate with the buji-pack4j-demo webapp that will be running at my laptop. 
3. Note down the following parameters for the app you have created. 
a. Identity Provider Single Sign-On URL
b. Identity Provider Issuer
c. X.509 Certificate
4. IDP metadata (entityID , md:NameIDFormat, md:SingleSignOnService Binding)
5. Install a secured version of tomcat running on port 8443 in your laptop using the instructions available at https://tomcat.apache.org/tomcat-8.0-doc/ssl-howto.html. 
6.  Using these information edit shiro.ini and change value for the keys formClient.loginUrl, clients.callbackUrl. 
7. Add saml2Client.maximumAuthenticationLifetime = 5000 to this ini file. 
8. Edit testshib.xml and delete one of the entity descriptor (there are two entity descriptors available to start with). 
9. Change entityId, DisplayName, description, X509Certificate, NameIDFormat, SingleSignOnService Binding and Location, Organization details and contact person details in this xml file. These values must match with the parameters for your app that was created at okta site. 

With these changes I can verify Authentication with SAML is successful and this webapp is able to fetch the profile details from the IdP. 

Thanks Jerome for the guidance and help. I am closing this issue. Thx,
